# Generated by Django 5.2.3 on 2025-07-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_project_description_alter_project_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
