# Generated by Django 5.2.3 on 2025-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта мэйл'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка на социальную сеть'),
        ),
    ]
