# Generated by Django 5.2.3 on 2025-07-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_contact_mail_contact_phone_number_alter_contact_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='url',
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram_url',
            field=models.URLField(null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_url',
            field=models.URLField(null=True, verbose_name='Ссылка на WhatsApp'),
        ),
    ]
