# Generated by Django 5.2.3 on 2025-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_remove_contact_url_contact_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=50, null=True, verbose_name='Почта мэйл'),
        ),
    ]
