# Generated by Django 5.2.3 on 2025-07-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_contact_address_alter_contact_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=20, verbose_name='Наименование услуги')),
                ('price_service', models.CharField(max_length=20, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
