# Generated by Django 5.2.3 on 2025-07-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='name_service',
            field=models.CharField(max_length=60, verbose_name='Наименование услуги'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_service',
            field=models.CharField(max_length=60, verbose_name='Цена услуги'),
        ),
    ]
