# Generated by Django 5.2.3 on 2025-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_price_name_service_alter_price_price_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название изображения')),
                ('image', models.ImageField(help_text='Загрузите сюда новое изображение для замены', upload_to='replaceable_images/', verbose_name='Новое изображение')),
                ('name_service', models.CharField(default='Wedding day', max_length=50, verbose_name='Вид услуги')),
                ('description', models.TextField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
