# Generated by Django 5.2.3 on 2025-07-16 03:40

import portfolio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='Загрузите сюда новое изображение для замены', upload_to='replaceable_images/', validators=[portfolio_app.models.validate_image_size], verbose_name='Новое изображение'),
        ),
    ]
